// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/scamsniff-home/AccessibilityFirst.tsx": () => import("../components/mockups/scamsniff-home/AccessibilityFirst.tsx"),
  "./components/mockups/scamsniff-home/AffordanceFirst.tsx": () => import("../components/mockups/scamsniff-home/AffordanceFirst.tsx"),
  "./components/mockups/scamsniff-home/HierarchyFirst.tsx": () => import("../components/mockups/scamsniff-home/HierarchyFirst.tsx")
};
